-- =============================================================
-- SEED: company_profile — Nifty 50, Nifty Next 50, and user portfolio stocks
-- Run AFTER market_schema.sql in Supabase SQL Editor.
-- Safe to re-run: uses ON CONFLICT DO UPDATE.
-- =============================================================

INSERT INTO company_profile (
  symbol, company_name, sector, industry, mcap_category,
  nse_symbol, bse_code, isin,
  founded_year, headquarters, ceo_name, employees,
  business_summary, thematic_tags, index_membership, listing_date
) VALUES

-- ── RELIANCE / ENERGY ──────────────────────────────────────────
('RELIANCE','Reliance Industries','Energy','Refineries & Petrochemicals','large',
 'RELIANCE','500325','INE002A01018',
 1966,'Mumbai, Maharashtra','Mukesh Ambani',236334,
 'India''s largest private-sector company operating across energy, petrochemicals, retail (Reliance Retail), and digital services (Jio Platforms).',
 ARRAY['conglomerate','energy','retail','telecom','5G','new-energy'],
 ARRAY['Nifty 50','Nifty 100','Sensex'],'1977-11-15'),

-- ── IT ─────────────────────────────────────────────────────────
('TCS','Tata Consultancy Services','IT','IT Services & Consulting','large',
 'TCS','532540','INE467B01029',
 1968,'Mumbai, Maharashtra','K Krithivasan',601546,
 'India''s largest IT services company providing IT, digital, and business solutions globally across banking, retail, manufacturing, and government sectors.',
 ARRAY['IT','outsourcing','cloud','AI','digital-transformation'],
 ARRAY['Nifty 50','Nifty 100','Sensex'],'2004-08-25'),

('INFY','Infosys','IT','IT Services & Consulting','large',
 'INFY','500209','INE009A01021',
 1981,'Bengaluru, Karnataka','Salil Parekh',317240,
 'Global technology services company offering IT consulting, software, BPO and engineering services. Strong presence in AI, cloud and digital transformation.',
 ARRAY['IT','cloud','AI','digital-transformation','ESG-leader'],
 ARRAY['Nifty 50','Nifty 100','Sensex'],'1993-06-14'),

('HCLTECH','HCL Technologies','IT','IT Services & Consulting','large',
 'HCLTECH','532281','INE860A01027',
 1976,'Noida, Uttar Pradesh','C Vijayakumar',225944,
 'IT services and products company known for HCLSoftware and strong engineering services. Focus on cloud-native, cybersecurity and digital process operations.',
 ARRAY['IT','cloud','cybersecurity','engineering-services'],
 ARRAY['Nifty 50','Nifty 100'],'1999-11-10'),

('WIPRO','Wipro','IT','IT Services & Consulting','large',
 'WIPRO','507685','INE075A01022',
 1945,'Bengaluru, Karnataka','Srinivas Pallia',221000,
 'Global IT, consulting and business-process company. Strong in cloud infrastructure, data analytics and cybersecurity.',
 ARRAY['IT','cloud','cybersecurity','ESG-leader'],
 ARRAY['Nifty 50','Nifty 100'],'1946-01-01'),

('TECHM','Tech Mahindra','IT','IT Services & Consulting','large',
 'TECHM','532755','INE669C01036',
 1986,'Pune, Maharashtra','Mohit Joshi',145000,
 'IT and BPO company with deep expertise in telecom, media and entertainment. Part of the Mahindra Group.',
 ARRAY['IT','telecom-tech','5G','AI'],
 ARRAY['Nifty 50','Nifty 100'],'2006-08-28'),

-- ── BANKING & FINANCIALS ────────────────────────────────────────
('HDFCBANK','HDFC Bank','Financial Services','Banking','large',
 'HDFCBANK','500180','INE040A01034',
 1994,'Mumbai, Maharashtra','Sashidhar Jagdishan',213527,
 'India''s largest private-sector bank by assets. Offers retail banking, wholesale banking and treasury operations. Merged with HDFC Ltd in 2023.',
 ARRAY['banking','retail-credit','mortgage','digital-banking'],
 ARRAY['Nifty 50','Nifty Bank','Sensex'],'1995-05-20'),

('ICICIBANK','ICICI Bank','Financial Services','Banking','large',
 'ICICIBANK','532174','INE090A01021',
 1994,'Mumbai, Maharashtra','Sandeep Bakhshi',129876,
 'India''s second-largest private-sector bank with a full suite of financial products including retail, corporate and international banking.',
 ARRAY['banking','retail-credit','digital-banking','insurance'],
 ARRAY['Nifty 50','Nifty Bank','Sensex'],'1997-09-17'),

('KOTAKBANK','Kotak Mahindra Bank','Financial Services','Banking','large',
 'KOTAKBANK','500247','INE237A01036',
 2003,'Mumbai, Maharashtra','Ashok Vaswani',92000,
 'Private-sector bank known for premium retail banking and wealth management. Expanded via merger with ING Vysya Bank in 2015.',
 ARRAY['banking','wealth-management','digital-banking'],
 ARRAY['Nifty 50','Nifty Bank'],'2003-12-20'),

('SBIN','State Bank of India','Financial Services','Banking','large',
 'SBIN','500112','INE062A01020',
 1955,'Mumbai, Maharashtra','Challa Sreenivasulu Setty',232296,
 'India''s largest public-sector bank with an unparalleled branch and ATM network. Offers retail, corporate, agriculture and government banking services.',
 ARRAY['banking','PSU','rural-banking','government'],
 ARRAY['Nifty 50','Nifty Bank','Sensex'],'1993-03-01'),

('AXISBANK','Axis Bank','Financial Services','Banking','large',
 'AXISBANK','532215','INE238A01034',
 1993,'Mumbai, Maharashtra','Amitabh Chaudhry',85000,
 'Third-largest private-sector bank in India. Strong in corporate banking, retail loans and digital payments. Acquired Citibank India retail business in 2023.',
 ARRAY['banking','digital-banking','retail-credit'],
 ARRAY['Nifty 50','Nifty Bank'],'1998-02-16'),

('BAJFINANCE','Bajaj Finance','Financial Services','NBFC','large',
 'BAJFINANCE','500034','INE296A01024',
 1987,'Pune, Maharashtra','Rajeev Jain',50000,
 'India''s largest NBFC offering consumer finance, SME lending, commercial lending and deposits. Pioneer in EMI-based retail financing.',
 ARRAY['NBFC','consumer-credit','SME-lending','fintech'],
 ARRAY['Nifty 50','Nifty 100'],'2010-04-01'),

('BAJAJFINSV','Bajaj Finserv','Financial Services','Diversified Financial Services','large',
 'BAJAJFINSV','532978','INE918I01026',
 2007,'Pune, Maharashtra','S S Rajagopal',80000,
 'Holding company for Bajaj Finance and Bajaj Allianz general/life insurance. One of India''s most diversified financial services conglomerates.',
 ARRAY['NBFC','insurance','financial-conglomerate'],
 ARRAY['Nifty 50','Nifty 100'],'2008-05-26'),

('INDUSINDBK','IndusInd Bank','Financial Services','Banking','large',
 'INDUSINDBK','532187','INE095A01012',
 1994,'Pune, Maharashtra','Sumant Kathpalia',30000,
 'Private-sector bank known for commercial vehicle financing, microfinance and corporate banking. Acquired Bharat Financial Inclusion (BFIL) in 2019.',
 ARRAY['banking','vehicle-finance','microfinance'],
 ARRAY['Nifty 50','Nifty Bank'],'1997-01-21'),

('SHRIRAMFIN','Shriram Finance','Financial Services','NBFC','large',
 'SHRIRAMFIN','511218','INE721A01047',
 1974,'Chennai, Tamil Nadu','Y S Chakravarti',74000,
 'India''s largest vehicle financing NBFC, especially for used commercial vehicles. Merged with Shriram City Union Finance in 2023.',
 ARRAY['NBFC','vehicle-finance','rural-lending'],
 ARRAY['Nifty 50','Nifty 100'],'2005-12-15'),

('HDFCLIFE','HDFC Life Insurance','Financial Services','Life Insurance','large',
 'HDFCLIFE','540777','INE795G01014',
 2000,'Mumbai, Maharashtra','Vibha Padalkar',20000,
 'One of India''s leading private life insurance companies offering individual and group insurance, pension and investment products.',
 ARRAY['insurance','life-insurance','wealth-management'],
 ARRAY['Nifty 50','Nifty 100'],'2017-11-17'),

('SBILIFE','SBI Life Insurance','Financial Services','Life Insurance','large',
 'SBILIFE','540719','INE123W01016',
 2001,'Mumbai, Maharashtra','Amit Jhingran',20000,
 'Joint venture between SBI and BNP Paribas Cardif. One of India''s top private life insurers with wide bancassurance network.',
 ARRAY['insurance','life-insurance','bancassurance'],
 ARRAY['Nifty 50','Nifty 100'],'2017-10-03'),

-- ── CONSUMER / FMCG ────────────────────────────────────────────
('HINDUNILVR','Hindustan Unilever','FMCG','FMCG','large',
 'HINDUNILVR','500696','INE030A01027',
 1933,'Mumbai, Maharashtra','Rohit Jawa',21000,
 'India''s largest FMCG company owning brands like Dove, Lux, Surf Excel, Horlicks, Knorr. Subsidiary of Unilever PLC.',
 ARRAY['FMCG','consumer-staples','D2C','ESG-leader'],
 ARRAY['Nifty 50','Nifty FMCG','Sensex'],'1995-01-01'),

('ITC','ITC','FMCG','Diversified FMCG','large',
 'ITC','500875','INE154A01025',
 1910,'Kolkata, West Bengal','Sanjiv Puri',31000,
 'Diversified conglomerate with dominant cigarette business and fast-growing FMCG brands (Aashirvaad, Sunfeast, Bingo). Also in hotels, agribusiness and paperboards.',
 ARRAY['FMCG','cigarettes','hospitality','agri','ESG-leader'],
 ARRAY['Nifty 50','Nifty FMCG','Sensex'],'1954-01-01'),

('BRITANNIA','Britannia Industries','FMCG','Food Processing','large',
 'BRITANNIA','500825','INE216A01030',
 1892,'Bengaluru, Karnataka','Rajneet Kohli',4100,
 'India''s leading biscuits and dairy company. Brands include Good Day, Marie Gold, Milkman. Major regional expansion in adjacencies.',
 ARRAY['FMCG','food','bakery','consumer-staples'],
 ARRAY['Nifty 50','Nifty FMCG'],'1946-01-01'),

('NESTLEIND','Nestle India','FMCG','Food Processing','large',
 'NESTLEIND','500790','INE239A01016',
 1912,'Gurugram, Haryana','Suresh Narayanan',8000,
 'Subsidiary of Nestle S.A. producing Maggi, KitKat, Munch and infant nutrition products. High-margin FMCG business with strong pricing power.',
 ARRAY['FMCG','food','nutrition','global-MNC'],
 ARRAY['Nifty 50','Nifty FMCG'],'1990-01-01'),

('TATACONSUM','Tata Consumer Products','FMCG','Beverages','large',
 'TATACONSUM','500800','INE192A01025',
 1962,'Kolkata, West Bengal','Sunil D''Souza',4500,
 'FMCG arm of the Tata Group managing brands like Tata Tea, Tata Salt, Tetley, Eight O''Clock Coffee and Tata Sampann.',
 ARRAY['FMCG','tea','food','Tata-group'],
 ARRAY['Nifty 50','Nifty FMCG'],'1998-07-03'),

-- ── AUTO ───────────────────────────────────────────────────────
('MARUTI','Maruti Suzuki India','Automobile','Passenger Vehicles','large',
 'MARUTI','532500','INE585B01010',
 1981,'New Delhi, Delhi','Hisashi Takeuchi',22000,
 'India''s largest passenger vehicle manufacturer with over 40% market share. Joint venture with Suzuki Motor Corporation of Japan.',
 ARRAY['auto','passenger-vehicles','EV-transition','rural'],
 ARRAY['Nifty 50','Nifty Auto','Sensex'],'2003-07-09'),

('TATAMOTORS','Tata Motors','Automobile','Diversified Auto','large',
 'TATAMOTORS','500570','INE155A01022',
 1945,'Mumbai, Maharashtra','Shailesh Chandra',81000,
 'Largest commercial vehicle maker in India; also owns Jaguar Land Rover (JLR). Pioneer in Indian EV with Nexon EV and Tiago EV.',
 ARRAY['auto','EV','commercial-vehicles','JLR','Tata-group'],
 ARRAY['Nifty 50','Nifty Auto'],'1998-09-10'),

('M&M','Mahindra & Mahindra','Automobile','Diversified Auto','large',
 'M&M','500520','INE101A01026',
 1945,'Mumbai, Maharashtra','Anish Shah',79000,
 'India''s leading SUV maker and world''s largest tractor manufacturer. Diversified across farm equipment, IT (Tech Mahindra), real estate and aerospace.',
 ARRAY['auto','SUV','EV','farm-equipment','conglomerate'],
 ARRAY['Nifty 50','Nifty Auto'],'1996-01-01'),

('BAJAJ-AUTO','Bajaj Auto','Automobile','Two & Three Wheelers','large',
 'BAJAJ-AUTO','532977','INE917I01010',
 1945,'Pune, Maharashtra','Rajiv Bajaj',10000,
 'World''s largest three-wheeler manufacturer and India''s second-largest two-wheeler maker. Strong export franchise covering 70+ countries.',
 ARRAY['auto','two-wheelers','three-wheelers','EV','exports'],
 ARRAY['Nifty 50','Nifty Auto'],'2008-05-26'),

('HEROMOTOCO','Hero MotoCorp','Automobile','Two-Wheelers','large',
 'HEROMOTOCO','500182','INE158A01026',
 1984,'New Delhi, Delhi','Niranjan Gupta',10000,
 'World''s largest two-wheeler manufacturer by volume, selling predominantly in India under the Hero brand after separation from Honda in 2010.',
 ARRAY['auto','two-wheelers','EV','rural'],
 ARRAY['Nifty 50','Nifty Auto'],'1991-01-01'),

('EICHERMOT','Eicher Motors','Automobile','Two-Wheelers & Commercial Vehicles','large',
 'EICHERMOT','505200','INE066A01021',
 1948,'New Delhi, Delhi','Siddhartha Lal',12000,
 'Parent of Royal Enfield, the iconic premium motorcycle brand. Also a JV partner in VE Commercial Vehicles (trucks). High-margin niche auto player.',
 ARRAY['auto','premium-motorcycles','commercial-vehicles','lifestyle'],
 ARRAY['Nifty 50','Nifty Auto'],'1997-08-12'),

-- ── PHARMA ─────────────────────────────────────────────────────
('SUNPHARMA','Sun Pharmaceutical Industries','Pharma','Pharmaceuticals','large',
 'SUNPHARMA','524715','INE044A01036',
 1983,'Mumbai, Maharashtra','Dilip Shanghvi',43000,
 'India''s largest pharma company by revenue. Strong in specialty branded generics (dermatology, ophthalmology, oncology) globally. Acquired Ranbaxy in 2015.',
 ARRAY['pharma','specialty-drugs','dermatology','oncology','exports'],
 ARRAY['Nifty 50','Nifty Pharma'],'1994-02-16'),

('DRREDDY','Dr. Reddy''s Laboratories','Pharma','Pharmaceuticals','large',
 'DRREDDY','500124','INE089A01023',
 1984,'Hyderabad, Telangana','Erez Israeli',24000,
 'Integrated pharma company with manufacturing, generics, branded generics and biosimilars business across 66 countries.',
 ARRAY['pharma','generics','biosimilars','CDMO','exports'],
 ARRAY['Nifty 50','Nifty Pharma'],'2001-04-11'),

('CIPLA','Cipla','Pharma','Pharmaceuticals','large',
 'CIPLA','500087','INE059A01026',
 1935,'Mumbai, Maharashtra','Umang Vohra',25000,
 'Pioneered affordable AIDS drugs globally. Major respiratory, cardiovascular and anti-infective pharma portfolio with strong US and South Africa presence.',
 ARRAY['pharma','generics','respiratory','affordable-medicines'],
 ARRAY['Nifty 50','Nifty Pharma'],'1995-02-22'),

-- ── CONSUMER DURABLES ───────────────────────────────────────────
('TITAN','Titan Company','Consumer Durables','Jewellery & Watches','large',
 'TITAN','500114','INE685A01028',
 1984,'Bengaluru, Karnataka','C K Venkataraman',13000,
 'India''s largest jewellery brand (Tanishq) and watch brand (Titan, Fastrack). Diversified into eyewear (Titan Eye+) and fragrances. Part of Tata Group.',
 ARRAY['jewellery','watches','luxury','consumer-discretionary','Tata-group'],
 ARRAY['Nifty 50','Nifty Consumer Durables'],'1995-08-01'),

('ASIANPAINT','Asian Paints','Consumer Durables','Paints & Coatings','large',
 'ASIANPAINT','500820','INE021A01026',
 1942,'Mumbai, Maharashtra','Amit Syngle',8000,
 'India''s largest paint company with 50%+ domestic market share. Present in 15 countries. Premium pricing power and strong distribution moat.',
 ARRAY['paints','consumer-durables','brand-moat','premiumisation'],
 ARRAY['Nifty 50','Nifty Consumer Durables','Sensex'],'1995-01-01'),

('APOLLOHOSP','Apollo Hospitals Enterprise','Healthcare','Hospitals & Diagnostics','large',
 'APOLLOHOSP','508869','INE437A01024',
 1983,'Chennai, Tamil Nadu','Suneeta Reddy',100000,
 'India''s largest private hospital chain with 70+ hospitals. Pioneer of corporate healthcare in India. Expanding digital health via Apollo 24|7.',
 ARRAY['healthcare','hospitals','digital-health','diagnostics'],
 ARRAY['Nifty 50','Nifty Healthcare'],'1979-01-01'),

-- ── CAPITAL GOODS / INFRA ───────────────────────────────────────
('LT','Larsen & Toubro','Capital Goods','Engineering & Construction','large',
 'LT','500510','INE018A01030',
 1938,'Mumbai, Maharashtra','S N Subrahmanyan',57000,
 'India''s largest engineering and construction conglomerate. Operates in infrastructure, power, defence, hydrocarbon and IT (L&T Technology, LTIMindtree).',
 ARRAY['infrastructure','defence','EPC','IT-services','government-projects'],
 ARRAY['Nifty 50','Nifty Infra','Sensex'],'1950-01-01'),

('ULTRACEMCO','UltraTech Cement','Construction Materials','Cement','large',
 'ULTRACEMCO','532538','INE481G01011',
 2004,'Mumbai, Maharashtra','Kailash Jhanwar',25000,
 'India''s largest cement company and the third-largest in the world (ex-China). Aditya Birla Group flagship in construction materials.',
 ARRAY['cement','infrastructure','construction','Aditya-Birla-group'],
 ARRAY['Nifty 50','Nifty 100'],'2004-07-29'),

('GRASIM','Grasim Industries','Diversified','Diversified','large',
 'GRASIM','500300','INE047A01021',
 1948,'Mumbai, Maharashtra','Himanshu Kapila',40000,
 'Aditya Birla Group flagship. World''s largest producer of viscose staple fibre; also controls UltraTech Cement and has paints JV (Birla Opus).',
 ARRAY['cement','textiles','paints','conglomerate','Aditya-Birla-group'],
 ARRAY['Nifty 50','Nifty 100'],'1947-01-01'),

-- ── METALS ─────────────────────────────────────────────────────
('TATASTEEL','Tata Steel','Metals & Mining','Steel','large',
 'TATASTEEL','500470','INE081A01020',
 1907,'Mumbai, Maharashtra','T V Narendran',81000,
 'One of world''s top 10 steel producers. Operations in India (Tata Steel BSL), Europe (Tata Steel Netherlands) and South-East Asia. Tata Group flagship.',
 ARRAY['steel','metals','Tata-group','Europe-operations'],
 ARRAY['Nifty 50','Nifty Metal'],'1995-01-01'),

('JSWSTEEL','JSW Steel','Metals & Mining','Steel','large',
 'JSWSTEEL','500228','INE019A01038',
 1982,'Mumbai, Maharashtra','Jayant Acharya',50000,
 'India''s largest steelmaker by capacity. JSW Group flagship. Expanding into US via Ohio operations; strong focus on EV-grade steel and downstream.',
 ARRAY['steel','metals','auto-steel','EV-material'],
 ARRAY['Nifty 50','Nifty Metal'],'1994-01-01'),

('HINDALCO','Hindalco Industries','Metals & Mining','Aluminium','large',
 'HINDALCO','500440','INE038A01020',
 1958,'Mumbai, Maharashtra','Satish Pai',65000,
 'World''s largest aluminium rolling company. Owns Novelis (largest recycled aluminium producer globally). Aditya Birla Group.',
 ARRAY['aluminium','copper','Novelis','auto-materials','Aditya-Birla-group'],
 ARRAY['Nifty 50','Nifty Metal'],'1958-01-01'),

-- ── ENERGY / OIL & GAS ─────────────────────────────────────────
('ONGC','Oil & Natural Gas Corporation','Energy','Oil Exploration & Production','large',
 'ONGC','500312','INE213A01029',
 1956,'New Delhi, Delhi','Arun Kumar Singh',33000,
 'India''s largest oil and gas exploration company. Produces ~70% of India''s domestic crude. Also holds HPCL stake and overseas assets via OVL.',
 ARRAY['oil-gas','exploration','PSU','energy-security'],
 ARRAY['Nifty 50','Nifty Energy','Nifty PSE'],'2004-08-17'),

('BPCL','Bharat Petroleum Corporation','Energy','Oil Refining & Marketing','large',
 'BPCL','500547','INE029A01011',
 1952,'Mumbai, Maharashtra','G Krishnakumar',12000,
 'India''s second-largest public-sector fuel retailer with refineries in Mumbai, Kochi and Bina. Owns Bharat Gas and Petronet LNG stake.',
 ARRAY['oil-gas','refinery','petrol-retail','PSU'],
 ARRAY['Nifty 50','Nifty Energy','Nifty PSE'],'1977-01-01'),

('IOC','Indian Oil Corporation','Energy','Oil Refining & Marketing','large',
 'IOC','530965','INE242A01010',
 1959,'New Delhi, Delhi','Shrikant Madhav Vaidya',33000,
 'India''s largest oil company by revenue with the highest refining capacity (1.4 mbpd). Operates IndianOil petrol stations, IndianOil Gas and petro-chemicals.',
 ARRAY['oil-gas','refinery','petrol-retail','PSU','Indane-LPG'],
 ARRAY['Nifty 100','Nifty PSE','Nifty Energy'],'1995-06-01'),

-- ── POWER ──────────────────────────────────────────────────────
('NTPC','NTPC','Power','Thermal & Renewable Power','large',
 'NTPC','532555','INE733E01010',
 1975,'New Delhi, Delhi','Gurdeep Singh',20000,
 'India''s largest power utility with ~70 GW installed capacity (thermal + solar). Central PSU; aggressively expanding into renewables targeting 60 GW by 2032.',
 ARRAY['power','PSU','coal','solar','renewable-energy','new-energy'],
 ARRAY['Nifty 50','Nifty Energy','Nifty PSE'],'2004-11-05'),

('POWERGRID','Power Grid Corporation of India','Power','Power Transmission','large',
 'POWERGRID','532898','INE752E01010',
 1989,'Gurugram, Haryana','Ravindra Kumar Tyagi',12000,
 'Central transmission utility of India owning and operating ~1.72 lakh circuit km of transmission lines with 99.97% grid availability.',
 ARRAY['power','transmission','PSU','InvIT','regulated-utility'],
 ARRAY['Nifty 50','Nifty Energy','Nifty PSE'],'2007-10-05'),

('ADANIGREEN','Adani Green Energy','Power','Renewable Power','large',
 'ADANIGREEN','541450','INE364U01010',
 2015,'Ahmedabad, Gujarat','Ashish Garg',5000,
 'World''s largest solar energy company by market cap. Targets 50 GW renewable capacity by 2030. Adani Group''s clean-energy flagship.',
 ARRAY['solar','wind','renewable-energy','ESG','new-energy','Adani-group'],
 ARRAY['Nifty 100','Nifty Energy'],'2018-06-18'),

-- ── TELECOM ────────────────────────────────────────────────────
('BHARTIARTL','Bharti Airtel','Telecom','Telecom Services','large',
 'BHARTIARTL','532454','INE397D01024',
 1995,'New Delhi, Delhi','Gopal Vittal',21000,
 'India''s largest telecom company by revenue. Operates in 18 African countries via Airtel Africa. Key player in 5G rollout and home broadband.',
 ARRAY['telecom','5G','Africa','broadband','enterprise'],
 ARRAY['Nifty 50','Nifty Telecom','Sensex'],'2002-02-15'),

-- ── COAL ───────────────────────────────────────────────────────
('COALINDIA','Coal India','Metals & Mining','Coal Mining','large',
 'COALINDIA','533278','INE522F01014',
 1975,'Kolkata, West Bengal','P M Prasad',227500,
 'World''s largest coal producer and India''s largest miner by volume. Supplies ~80% of India''s thermal coal requirements. High-dividend PSU.',
 ARRAY['coal','PSU','high-dividend','energy-security'],
 ARRAY['Nifty 50','Nifty PSE'],'2010-11-04'),

-- ── CEMENT ─────────────────────────────────────────────────────
('ADANIENT','Adani Enterprises','Diversified','Diversified','large',
 'ADANIENT','512599','INE423A01024',
 1988,'Ahmedabad, Gujarat','Gautam Adani',45000,
 'Flagship of the Adani Group acting as incubator for new businesses including airports, roads, data centers, solar manufacturing and defence.',
 ARRAY['airports','defence','green-energy','data-centers','conglomerate','Adani-group'],
 ARRAY['Nifty 50','Nifty 100'],'1994-06-28'),

('ADANIPORTS','Adani Ports & SEZ','Services','Port & Logistics','large',
 'ADANIPORTS','532921','INE742F01042',
 1998,'Ahmedabad, Gujarat','Karan Adani',30000,
 'India''s largest commercial port operator managing 13+ ports. Also operates logistics, industrial SEZ and warehousing via APSEZ.',
 ARRAY['ports','logistics','SEZ','infrastructure','Adani-group'],
 ARRAY['Nifty 50','Nifty 100'],'2008-05-27'),

-- ── ZOMATO / INTERNET ──────────────────────────────────────────
('ZOMATO','Zomato','Consumer Services','Online Food Delivery','large',
 'ZOMATO','543320','INE758T01015',
 2008,'Gurugram, Haryana','Deepinder Goyal',5500,
 'India''s largest food delivery platform with Blinkit quick commerce. Expanding into dining-out, hyperpure B2B supplies and events (District).',
 ARRAY['food-tech','quick-commerce','D2C','internet','new-age'],
 ARRAY['Nifty 50','Nifty 100'],'2021-07-23'),

-- ── USER PORTFOLIO STOCKS (not Nifty 50) ───────────────────────
('HAL','Hindustan Aeronautics','Capital Goods','Defence Aerospace','large',
 'HAL','541153','INE066F01020',
 1940,'Bengaluru, Karnataka','C B Ananthakrishnan',30000,
 'India''s premier defence aerospace company manufacturing aircraft, helicopters, engines and avionics for Indian armed forces. Core to Atmanirbhar Bharat.',
 ARRAY['defence','aerospace','PSU','government-contracts','Make-in-India'],
 ARRAY['Nifty 100','Nifty Defence','Nifty PSE'],'2018-03-28'),

('BEL','Bharat Electronics','Capital Goods','Defence Electronics','large',
 'BEL','263534','INE263A01024',
 1954,'Bengaluru, Karnataka','Bhanu Prakash Srivastava',11000,
 'Navratna PSU manufacturing defence electronics including radars, sonars, EW systems, communication equipment and civilian electronics.',
 ARRAY['defence','electronics','PSU','radar','government-contracts','Make-in-India'],
 ARRAY['Nifty 50','Nifty Defence','Nifty PSE'],'1992-08-19'),

('DLF','DLF','Real Estate','Real Estate Development','large',
 'DLF','532868','INE271C01023',
 1946,'New Delhi, Delhi','Ashok Tyagi',4000,
 'India''s largest real estate developer by market cap. Known for DLF Cyber City (premium offices) and luxury residential projects in NCR and other cities.',
 ARRAY['real-estate','commercial-offices','luxury-residential','REITs'],
 ARRAY['Nifty 100','Nifty Realty'],'2007-07-05'),

('CUMMINS','Cummins India','Capital Goods','Industrial Engines','large',
 'CUMMINS','500480','INE298A01020',
 1962,'Pune, Maharashtra','Ashwath Ram',6000,
 'Subsidiary of Cummins Inc. USA. Manufactures diesel and natural gas engines and power generation equipment. Strong in data-center gensets and industrial power.',
 ARRAY['engines','power-generation','data-center','industrial','global-MNC'],
 ARRAY['Nifty 100','Nifty Midcap'],'1995-01-01'),

('BLUESTAR','Blue Star','Consumer Durables','Air Conditioning','mid',
 'BLUESTAR','500067','INE472A01039',
 1943,'Mumbai, Maharashtra','B Thiagarajan',6500,
 'India''s leading commercial air-conditioning company. Growing fast in residential AC market. Also in refrigeration and MEP contracting.',
 ARRAY['air-conditioning','HVAC','consumer-durables','cooling','summer-play'],
 ARRAY['Nifty 500','Nifty Midcap 100'],'1992-01-01'),

('ORIENTELEC','Orient Electric','Consumer Durables','Consumer Electronics & Appliances','mid',
 'ORIENTELEC','541301','INE142Z01019',
 1954,'New Delhi, Delhi','Rakesh Khanna',3000,
 'CK Birla Group company making fans, lighting, home appliances and EV chargers. Market leader in ceiling fans; expanding in premium appliances.',
 ARRAY['fans','lighting','consumer-durables','EV-charging','CK-Birla-group'],
 ARRAY['Nifty 500'],'2018-05-21'),

('GODREJIND','Godrej Industries','Diversified','Diversified','large',
 'GODREJIND','500164','INE233A01035',
 1897,'Mumbai, Maharashtra','Pirojsha Godrej',40000,
 'Holding company of the Godrej Group with businesses in chemicals, real estate (Godrej Properties), consumer products and agriculture (Agrovet).',
 ARRAY['chemicals','real-estate','consumer-products','agriculture','conglomerate','Godrej-group'],
 ARRAY['Nifty 500'],'1994-01-01'),

('HATHWAY','Hathway Cable & Datacom','Telecom','Cable TV & Broadband','small',
 'HATHWAY','533162','INE982F01036',
 1959,'Mumbai, Maharashtra','Rajan Gupta',5000,
 'One of India''s largest cable TV operators and growing broadband ISP. Backed by Reliance Industries post-2019 acquisition.',
 ARRAY['cable-TV','broadband','last-mile','Reliance-backed'],
 ARRAY['Nifty 500'],'2010-02-25'),

('ASTERDM','Aster DM Healthcare','Healthcare','Hospitals','mid',
 'ASTERDM','540975','INE914M01019',
 1987,'Bengaluru, Karnataka','Alisha Moopen',23000,
 'Multi-specialty hospital chain primarily in South India with significant presence in GCC countries (Gulf). Owns Aster hospitals, clinics and pharmacies.',
 ARRAY['healthcare','hospitals','GCC','diagnostics','pharma-retail'],
 ARRAY['Nifty 500','Nifty Healthcare'],'2018-02-26'),

('RPOWER','Reliance Power','Power','Power Generation','small',
 'RPOWER','500390','INE614G01033',
 1995,'Mumbai, Maharashtra','Anil Ambani',3000,
 'Anil Ambani Group power company with thermal, gas and renewable capacity. Went through significant financial stress; restructuring ongoing.',
 ARRAY['power','thermal','renewable-energy','debt-restructuring'],
 ARRAY['Nifty 500'],'2008-02-15'),

('STERLINW','Sterling and Wilson Renewable Energy','Power','EPC Solar','mid',
 'STERLINW','543209','INE00M201021',
 1979,'Mumbai, Maharashtra','Khurshed Daruvala',4000,
 'Global solar EPC company executing large-scale utility solar projects across India, Middle East, Africa and South-East Asia. Backed by Shapoorji Pallonji Group.',
 ARRAY['solar','EPC','renewable-energy','international-projects'],
 ARRAY['Nifty 500'],'2019-08-20'),

('APEX','Apex Frozen Foods','Food Processing','Seafood Processing & Export','small',
 'APEX','540695','INE346W01013',
 1995,'Kakinada, Andhra Pradesh','A Satish Kumar',2000,
 'Leading shrimp and seafood processor and exporter. Sells branded frozen shrimp to USA, EU and Japan. Integrated from hatchery to processing.',
 ARRAY['seafood','aquaculture','exports','food-processing','small-cap'],
 ARRAY['Nifty 500'],'2017-08-09'),

('TREJHARA','Trejhara Solutions','IT','IT Products & Services','small',
 'TREJHARA','543227','INE00CA01015',
 2002,'Mumbai, Maharashtra','Vikram Gupta',500,
 'Small-cap IT company offering enterprise applications, cloud and AI solutions. Listed under SME category.',
 ARRAY['IT','small-cap','enterprise-software'],
 ARRAY['Nifty 500'],'2021-04-27'),

('VIYASHSCI','Viyash Scientific','Healthcare','Medical Devices','small',
 'VIYASHSCI','543765','INE807F01027',
 2008,'Bengaluru, Karnataka','Viyash Founder',200,
 'Small-cap medical devices and scientific instruments company.',
 ARRAY['medical-devices','healthcare','small-cap'],
 ARRAY[],'2022-01-01'),

-- ── NIFTY NEXT 50 — ADDITIONAL MAJORS ─────────────────────────
('AMBUJACEM','Ambuja Cements','Construction Materials','Cement','large',
 'AMBUJACEM','500425','INE079A01024',
 1983,'Ahmedabad, Gujarat','Ajay Kapur',6000,
 'Second-largest cement company in India by capacity. Acquired by Adani Group from Holcim in 2022. Strong in western and northern India.',
 ARRAY['cement','infrastructure','Adani-group'],
 ARRAY['Nifty 100'],'1993-09-14'),

('ACC','ACC','Construction Materials','Cement','large',
 'ACC','500410','INE012A01025',
 1936,'Mumbai, Maharashtra','Ajay Kapur',10000,
 'One of India''s oldest cement companies. Acquired by Adani Group from Holcim in 2022. Pioneer in sustainable cement and Ready Mix Concrete.',
 ARRAY['cement','infrastructure','Adani-group','RMC'],
 ARRAY['Nifty 100'],'1947-01-01'),

('SIEMENS','Siemens India','Capital Goods','Industrial Automation & Digitalization','large',
 'SIEMENS','500550','INE003A01024',
 1867,'Mumbai, Maharashtra','Sunil Mathur',11000,
 'Indian subsidiary of Siemens AG. Manufactures power distribution equipment, industrial automation, smart infrastructure and mobility solutions.',
 ARRAY['automation','power-grid','smart-infra','global-MNC','digitalization'],
 ARRAY['Nifty 100'],'1958-01-01'),

('ABB','ABB India','Capital Goods','Electrical Equipment','large',
 'ABB','500002','INE117A01022',
 1949,'Bengaluru, Karnataka','Sanjeev Sharma',6000,
 'Indian subsidiary of ABB Ltd Switzerland. Provides electrification, automation and robotics solutions to utilities, industry and transport.',
 ARRAY['automation','robotics','electrification','global-MNC'],
 ARRAY['Nifty 100'],'1949-01-01'),

('HAVELLS','Havells India','Consumer Durables','Electrical Equipment','large',
 'HAVELLS','517354','INE176B01034',
 1958,'Gurugram, Haryana','Anil Rai Gupta',16000,
 'Leading electrical equipment company owning brands like Havells, Lloyd (AC), Crabtree and Standard. Strong dealer network across India.',
 ARRAY['electrical-equipment','consumer-durables','AC','EV-charging'],
 ARRAY['Nifty 100'],'1992-01-01'),

('ADANIPOWER','Adani Power','Power','Thermal Power Generation','large',
 'ADANIPOWER','533096','INE814H01011',
 1996,'Ahmedabad, Gujarat','Anil Sardana',7000,
 'India''s largest private thermal power producer. Operates ~15.2 GW of coal-based capacity across Gujarat, Maharashtra, Rajasthan and Jharkhand.',
 ARRAY['thermal-power','coal','PSU-competitor','Adani-group'],
 ARRAY['Nifty 100'],'2009-08-20'),

('PIDILITIND','Pidilite Industries','Chemicals','Specialty Chemicals','large',
 'PIDILITIND','500331','INE318A01026',
 1959,'Mumbai, Maharashtra','Bharat Puri',14000,
 'Maker of Fevicol, Dr. Fixit and Fevikwik with near-monopoly in adhesives. Expanding into construction chemicals and waterproofing.',
 ARRAY['adhesives','specialty-chemicals','brand-moat','construction-chemicals'],
 ARRAY['Nifty 100'],'1995-01-01'),

('DMART','Avenue Supermarts (D-Mart)','Consumer Services','Supermarkets','large',
 'DMART','540376','INE192R01011',
 2002,'Mumbai, Maharashtra','Neville Noronha',13000,
 'India''s most profitable supermarket chain operating D-Mart stores. EDLP (everyday low prices) model with owned properties drives very high returns on capital.',
 ARRAY['retail','FMCG-distribution','supermarket','EDLP'],
 ARRAY['Nifty 100'],'2017-03-21'),

('PERSISTENT','Persistent Systems','IT','IT Services','large',
 'PERSISTENT','533179','INE262H01021',
 1990,'Pune, Maharashtra','Sandeep Kalra',22000,
 'Fast-growing mid-cap IT services company strong in digital engineering, AI and BFSI verticals. Among the best-performing IT companies in revenue growth.',
 ARRAY['IT','digital-engineering','AI','BFSI-tech'],
 ARRAY['Nifty Midcap 50'],'2010-03-06'),

('POLYCAB','Polycab India','Capital Goods','Wires & Cables','large',
 'POLYCAB','542652','INE704P01022',
 1964,'Mumbai, Maharashtra','Inder T Jaisinghani',9500,
 'India''s largest wires and cables company. Also manufactures FMEG products (fans, lights, switches). Key beneficiary of infra and real estate boom.',
 ARRAY['wires-cables','electricals','infra-play','real-estate-proxy'],
 ARRAY['Nifty 100'],'2019-04-16'),

('CHOLAFIN','Cholamandalam Investment and Finance','Financial Services','NBFC','large',
 'CHOLAFIN','590005','INE121A01024',
 1978,'Chennai, Tamil Nadu','D Arul Selvan',18000,
 'Murugappa Group NBFC offering vehicle finance, home loans and SME finance. One of India''s best-managed NBFCs with consistent asset quality.',
 ARRAY['NBFC','vehicle-finance','home-loans','Murugappa-group'],
 ARRAY['Nifty 100'],'1976-01-01'),

('MUTHOOTFIN','Muthoot Finance','Financial Services','Gold Loans','large',
 'MUTHOOTFIN','533398','INE414G01012',
 1939,'Kochi, Kerala','George Alexander Muthoot',28000,
 'India''s largest gold loan NBFC. Over 5,600 branches. Key beneficiary of gold price rises and unorganised lending formalization.',
 ARRAY['gold-loan','NBFC','rural-lending','financial-inclusion'],
 ARRAY['Nifty 100'],'2011-05-06'),

('TRENT','Trent','Consumer Services','Fashion Retail','large',
 'TRENT','500251','INE849A01020',
 1998,'Mumbai, Maharashtra','P V Sheshadri',14000,
 'Tata Group fashion retailer owning Westside and fast-fashion brand Zudio. One of India''s fastest-growing organized retail chains.',
 ARRAY['retail','fashion','fast-fashion','Zudio','Tata-group'],
 ARRAY['Nifty 100'],'1998-08-04'),

('IRFC','Indian Railway Finance Corporation','Financial Services','Government Financing','large',
 'IRFC','543257','INE053F01010',
 1986,'New Delhi, Delhi','Manoj Kumar Dubey',30,
 'Dedicated market borrowing arm of the Indian Railways. Raises funds for rolling stock and infrastructure. Zero credit risk as GoI-guaranteed entity.',
 ARRAY['railways','government','PSU','infrastructure-finance','high-dividend'],
 ARRAY['Nifty 100','Nifty PSE'],'2021-01-29'),

('RECLTD','REC Limited','Financial Services','Infrastructure Finance','large',
 'RECLTD','532955','INE020B01018',
 1969,'New Delhi, Delhi','Vivek Kumar Dewangan',700,
 'Government NBFC financing power sector projects including generation, transmission and distribution. Co-finances renewable energy with PFC.',
 ARRAY['power-finance','PSU','renewable-energy','infrastructure-finance','high-dividend'],
 ARRAY['Nifty 100','Nifty PSE'],'2008-03-12'),

('PFC','Power Finance Corporation','Financial Services','Infrastructure Finance','large',
 'PFC','532810','INE134E01011',
 1986,'New Delhi, Delhi','Parminder Chopra',600,
 'Navratna PSU NBFC providing long-term finance to power sector entities. Holds majority stake in REC Ltd. Key enabler of India''s power sector investments.',
 ARRAY['power-finance','PSU','renewable-energy','infrastructure-finance','high-dividend'],
 ARRAY['Nifty 100','Nifty PSE'],'2007-02-23'),

('NHPC','NHPC','Power','Hydroelectric Power','large',
 'NHPC','533098','INE848E01016',
 1975,'Faridabad, Haryana','Rajendra Prasad Goyal',14000,
 'India''s largest hydroelectric power generator and Navratna PSU. Expanding into solar and wind with 10 GW renewable target by 2030.',
 ARRAY['hydro-power','renewable-energy','PSU','government-contracts'],
 ARRAY['Nifty 100','Nifty PSE'],'2009-08-01'),

('MEESHO','Meesho','Consumer Services','Social Commerce','small',
 'MEESHO','543571','INE0VDM01015',
 2015,'Bengaluru, Karnataka','Vidit Aatrey',15000,
 'India''s largest social commerce / reseller marketplace targeting Tier 2+ towns. Backed by SoftBank and Fidelity. Profitable as of FY24.',
 ARRAY['e-commerce','social-commerce','Tier2-India','new-age','internet'],
 ARRAY[],'2024-01-01')

ON CONFLICT (symbol) DO UPDATE SET
  company_name     = EXCLUDED.company_name,
  sector           = EXCLUDED.sector,
  industry         = EXCLUDED.industry,
  mcap_category    = EXCLUDED.mcap_category,
  nse_symbol       = EXCLUDED.nse_symbol,
  bse_code         = EXCLUDED.bse_code,
  isin             = EXCLUDED.isin,
  founded_year     = EXCLUDED.founded_year,
  headquarters     = EXCLUDED.headquarters,
  ceo_name         = EXCLUDED.ceo_name,
  employees        = EXCLUDED.employees,
  business_summary = EXCLUDED.business_summary,
  thematic_tags    = EXCLUDED.thematic_tags,
  index_membership = EXCLUDED.index_membership,
  listing_date     = EXCLUDED.listing_date,
  updated_at       = NOW();

-- ── VERIFICATION ───────────────────────────────────────────────
-- Run this after the INSERT to confirm the seed worked:
-- SELECT COUNT(*) FROM company_profile;
-- SELECT symbol, company_name, sector, mcap_category FROM company_profile ORDER BY symbol;
